[package]
name = "emuella-j2k-container"
description = "JP2 and JPH container boundary for emuella-j2k."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["std"]
std = []

[lints]
workspace = true
