/*
 * Experimental Emuella JPEG 2000 C ABI, version zero.
 *
 * Every non-null pointer must remain valid and correctly aligned for its
 * complete synchronous call. Writable outputs must not overlap one another,
 * input storage, Rust-owned handles or callback destinations. An opaque handle
 * must be the exact live value returned by this library and must be destroyed
 * exactly once after all calls using it have quiesced; destroy accepts null.
 *
 * A decoder borrows the source context until decoder destruction. The source
 * bytes, length and context identity must remain unchanged, and read_at must be
 * safe for concurrent invocation, fill the requested range completely, retain
 * no destination pointer, avoid related-handle re-entry and return without
 * unwinding. See the complete contract at
 * https://github.com/emuella/emuella-j2k/blob/main/docs/c-abi-safety-contract.md.
 */


#ifndef EMUELLA_J2K_H
#define EMUELLA_J2K_H

/* Generated by cbindgen 0.29.4. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Experimental ABI version. Major zero carries no compatibility promise.
 */
#define EMUELLA_J2K_ABI_VERSION 0

#define EMUELLA_J2K_ENDIAN_BIG 2

#define EMUELLA_J2K_ENDIAN_LITTLE 1

#define EMUELLA_J2K_ENDIAN_NONE 0

typedef struct EmuellaJ2kDecoder EmuellaJ2kDecoder;

typedef struct EmuellaJ2kError EmuellaJ2kError;

typedef struct EmuellaJ2kImage EmuellaJ2kImage;

typedef struct EmuellaJ2kInspection EmuellaJ2kInspection;

typedef struct EmuellaJ2kWorkspace EmuellaJ2kWorkspace;

typedef uint32_t EmuellaJ2kStatus;

/**
 * One-component decode request in full-resolution image-relative coordinates.
 */
typedef struct EmuellaJ2kDecodeRequestV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint16_t component;
  /**
   * Zero means all quality layers; otherwise the leading layer count.
   */
  uint16_t max_quality_layers;
  uint32_t x;
  uint32_t y;
  uint32_t width;
  uint32_t height;
  uint8_t discard_levels;
  uint8_t reserved_bytes[7];
} EmuellaJ2kDecodeRequestV0;

/**
 * One to four distinct components in caller order, sharing one regional plan.
 * The four-component bound belongs to this ABI, not codec admission. Unused
 * component slots and reserved fields must be zero. Collection is opt-in.
 */
typedef struct EmuellaJ2kDecodeComponentsRequestV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint16_t component_count;
  /**
   * Zero means all quality layers; otherwise the leading layer count.
   */
  uint16_t max_quality_layers;
  uint16_t components[4];
  uint32_t x;
  uint32_t y;
  uint32_t width;
  uint32_t height;
  uint8_t discard_levels;
  /**
   * Zero disables observations; one collects execution work counters.
   */
  uint8_t collect_work;
  uint8_t reserved_bytes[6];
} EmuellaJ2kDecodeComponentsRequestV0;

/**
 * A positioned-read callback fills the complete requested destination range.
 * Any non-zero return is translated to source I/O failure.
 */
typedef EmuellaJ2kStatus (*EmuellaJ2kReadAtFn)(void *context,
                                               uint64_t offset,
                                               uint8_t *destination,
                                               size_t length);

/**
 * Consumer-owned positioned source descriptor borrowed by a decoder.
 */
typedef struct EmuellaJ2kSourceV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint64_t length;
  void *context;
  EmuellaJ2kReadAtFn read_at;
} EmuellaJ2kSourceV0;

/**
 * Native raw-component geometry and sample representation.
 */
typedef struct EmuellaJ2kComponentInfoV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint16_t source_component;
  uint8_t bits_per_sample;
  uint8_t is_signed;
  uint8_t byte_order;
  uint8_t horizontal_separation;
  uint8_t vertical_separation;
  uint8_t reserved_byte;
  uint32_t width;
  uint32_t height;
  uint32_t x_origin;
  uint32_t y_origin;
} EmuellaJ2kComponentInfoV0;

/**
 * Immutable observations for one successful decode with collect_work enabled.
 * Work includes unrequested MCT dependencies. Capacities are retained storage,
 * not allocation counts or per-call growth. Source callback bytes are excluded.
 */
typedef struct EmuellaJ2kDecodeWorkV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  /**
   * Exactly one preparation per successful call; plans are not cached.
   */
  uint64_t preparation_count;
  uint64_t code_blocks_decoded;
  uint64_t tier1_coefficients;
  uint64_t dwt_samples;
  uint64_t synthesis_coefficients_loaded;
  uint64_t synthesis_horizontal_values;
  uint64_t synthesis_vertical_values;
  uint64_t synthesis_lifting_updates;
  uint64_t synthesis_output_samples;
  uint64_t windowed_synthesis_component_tiles;
  uint64_t full_synthesis_component_tiles;
  /**
   * Logical bytes requested for the new C ABI owned output-plane buffers.
   * Excludes descriptors, plans, workspace, allocator metadata and copies.
   */
  uint64_t output_allocation_bytes;
  /**
   * Actual combined capacity in bytes of those output-plane buffers.
   */
  uint64_t output_capacity_bytes;
  /**
   * Largest retained code-block coefficient capacity, in sample slots.
   */
  uint64_t coefficient_capacity;
  /**
   * Retained fragmented codeword assembly capacity, in bytes.
   */
  uint64_t segment_capacity;
  /**
   * Largest retained tile-axis transform scratch capacity, in sample slots.
   */
  uint64_t transform_capacity;
  /**
   * Largest retained full coefficient-plane capacity, in sample slots.
   */
  uint64_t full_coefficient_plane_capacity;
  /**
   * Largest retained full-transform scratch capacity, in sample slots.
   */
  uint64_t full_transform_scratch_capacity;
  /**
   * Successful output-plane buffer reservation requests in this C ABI call.
   * Excludes all other allocations; this is not a process allocator count.
   */
  uint64_t output_allocation_count;
  /**
   * Capacity-based heap bytes retained by the complete workspace after this
   * execution, including private workers; excludes allocator metadata.
   */
  uint64_t workspace_retained_heap_bytes;
} EmuellaJ2kDecodeWorkV0;

/**
 * Reference-image properties or decoded image properties.
 */
typedef struct EmuellaJ2kImageInfoV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint32_t width;
  uint32_t height;
  uint16_t component_count;
  uint8_t bits_per_sample;
  uint8_t is_signed;
  uint8_t byte_order;
  uint8_t reserved_bytes[7];
} EmuellaJ2kImageInfoV0;

#define EMUELLA_J2K_STATUS_INTERNAL 6

#define EMUELLA_J2K_STATUS_INVALID_ARGUMENT 1

#define EMUELLA_J2K_STATUS_INVALID_INPUT 2

#define EMUELLA_J2K_STATUS_OK 0

#define EMUELLA_J2K_STATUS_PANIC 7

#define EMUELLA_J2K_STATUS_RESOURCE_LIMIT 5

#define EMUELLA_J2K_STATUS_SOURCE_IO 4

#define EMUELLA_J2K_STATUS_UNSUPPORTED 3

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t emuella_j2k_abi_version(void);

/**
 * Decode one component region into a new immutable Rust-owned image.
 *
 * # Safety
 * `decoder` and `workspace` must be null or exact live handles of their
 * respective types from this library, kept alive for the call. No other active
 * operation may use this workspace. The decoder creation-time source and
 * callback obligations still apply, including concurrent callback safety.
 * `request` must contain a readable, initialised size/version prefix and, when
 * it advertises the supported full size, the complete initialised request. `output` must
 * provide writable storage for one value of its declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_decode_component_region(const struct EmuellaJ2kDecoder *decoder,
                                                     const struct EmuellaJ2kWorkspace *workspace,
                                                     const struct EmuellaJ2kDecodeRequestV0 *request,
                                                     struct EmuellaJ2kImage **output,
                                                     struct EmuellaJ2kError **error_output);

/**
 * Decode selected components of one region into a new immutable Rust-owned image.
 * Planes follow request order. Failure clears output to null; workspace scratch
 * may grow on failure. No partially decoded image is published.
 *
 * # Safety
 * `decoder` and `workspace` must be null or exact live handles of their
 * respective types from this library, kept alive for the call. No other active
 * operation may use this workspace. The decoder creation-time source and
 * callback obligations still apply, including concurrent callback safety.
 * `request` must contain a readable, initialised size/version prefix and, when
 * it advertises the supported full size, the complete initialised request. `output` must
 * provide writable storage for one value of its declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_decode_components_region(const struct EmuellaJ2kDecoder *decoder,
                                                      const struct EmuellaJ2kWorkspace *workspace,
                                                      const struct EmuellaJ2kDecodeComponentsRequestV0 *request,
                                                      struct EmuellaJ2kImage **output,
                                                      struct EmuellaJ2kError **error_output);

/**
 * Create a decoder that borrows the source descriptor's context and callback.
 *
 * # Safety
 * `source` must contain a readable, initialised size/version prefix; if it
 * advertises the supported full size, the complete source structure must be
 * readable and initialised. The descriptor is copied. Its callback, context,
 * stable length and immutable source bytes must remain valid until the returned
 * decoder is destroyed and all its operations finish. The callback must support
 * concurrent calls, fill each successful requested range, retain no destination,
 * neither re-enter related handles nor destroy or mutate any Emuella handle,
 * and return normally without unwinding. `output` must provide writable storage for one value
 * of its declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_decoder_create(const struct EmuellaJ2kSourceV0 *source,
                                            struct EmuellaJ2kDecoder **output,
                                            struct EmuellaJ2kError **error_output);

/**
 * Destroy a decoder after all calls and callbacks using it have quiesced.
 *
 * # Safety
 * `decoder` must be null or the exact live decoder handle returned by this
 * library. A non-null handle transfers ownership back exactly once; all calls,
 * callbacks and borrowed observations using it must have quiesced. It must not
 * be used again or destroyed concurrently.
 */
void emuella_j2k_decoder_destroy(struct EmuellaJ2kDecoder *decoder);

/**
 * Inspect raw Part 1 geometry without decoding packet bodies.
 *
 * # Safety
 * `decoder` must be null or an exact live decoder from this library, kept
 * alive for the call. Its creation-time source and callback obligations still
 * apply, including concurrent callback safety. `output` must provide writable storage for one
 * value of its declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_decoder_inspect(const struct EmuellaJ2kDecoder *decoder,
                                             struct EmuellaJ2kInspection **output,
                                             struct EmuellaJ2kError **error_output);

/**
 * Destroy an immutable diagnostic handle.
 *
 * # Safety
 * `error` must be null or the exact live error handle returned by this
 * library. A non-null handle transfers ownership back exactly once; all calls,
 * callbacks and borrowed observations using it must have quiesced. It must not
 * be used again or destroyed concurrently.
 */
void emuella_j2k_error_destroy(struct EmuellaJ2kError *error);

/**
 * Copy the complete NUL-terminated UTF-8 diagnostic into caller storage.
 *
 * # Safety
 * `error` must be null or an exact live diagnostic from this library, with
 * no destruction during the call. `destination` must provide `capacity`
 * exclusively writable bytes disjoint from the diagnostic allocation.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_error_message_copy(const struct EmuellaJ2kError *error,
                                                uint8_t *destination,
                                                size_t capacity);

/**
 * Return the diagnostic byte count, including its terminating NUL byte.
 *
 * # Safety
 * `error` must be null or an exact live diagnostic from this library, with
 * no destruction during the call. `output` must provide exclusive writable
 * storage for one usize, disjoint from the diagnostic allocation.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_error_message_size(const struct EmuellaJ2kError *error,
                                                size_t *output);

/**
 * Return the status retained by an immutable diagnostic handle.
 *
 * # Safety
 * `error` must be null or an exact live diagnostic from this library, with
 * no destruction during the call. Concurrent immutable observations are allowed.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_error_status(const struct EmuellaJ2kError *error);

/**
 * Copy the first decoded component descriptor into caller-owned storage.
 *
 * # Safety
 * `image` must be null or an exact live image handle from this library,
 * kept alive without destruction throughout the call. Concurrent immutable
 * observations are allowed. `output` must provide writable storage for one value of its
 * declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_image_component_info(const struct EmuellaJ2kImage *image,
                                                  struct EmuellaJ2kComponentInfoV0 *output,
                                                  struct EmuellaJ2kError **error_output);

/**
 * Copy the descriptor at a zero-based output position in request order.
 *
 * # Safety
 * `image` must be null or an exact live image handle from this library,
 * kept alive without destruction throughout the call. Concurrent immutable
 * observations are allowed. `output` must provide writable storage for one value of its
 * declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_image_component_info_at(const struct EmuellaJ2kImage *image,
                                                     uint16_t output_index,
                                                     struct EmuellaJ2kComponentInfoV0 *output,
                                                     struct EmuellaJ2kError **error_output);

/**
 * Copy the first output component into a bounded buffer with explicit row stride.
 *
 * # Safety
 * `image` must be null or an exact live image from this library, kept alive
 * throughout the copy. `destination` must provide `capacity` exclusively writable
 * bytes, disjoint from the image and all other inputs and outputs. The checked
 * stride and capacity determine the rows written. A non-null `error_output`
 * must provide writable storage for one error pointer, owned by the caller on
 * return and released once with `emuella_j2k_error_destroy`.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_image_copy(const struct EmuellaJ2kImage *image,
                                        uint8_t *destination,
                                        size_t capacity,
                                        size_t stride_bytes,
                                        struct EmuellaJ2kError **error_output);

/**
 * Copy rows at a zero-based output position in request order with explicit stride.
 * Bounds failure leaves destination bytes unchanged; successful copies preserve
 * row padding. This operation does not decode directly into foreign storage.
 *
 * # Safety
 * `image` must be null or an exact live image from this library, kept alive
 * throughout the copy. `destination` must provide `capacity` exclusively writable
 * bytes, disjoint from the image and all other inputs and outputs. The checked
 * stride and capacity determine the rows written. A non-null `error_output`
 * must provide writable storage for one error pointer, owned by the caller on
 * return and released once with `emuella_j2k_error_destroy`.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_image_copy_component(const struct EmuellaJ2kImage *image,
                                                  uint16_t output_index,
                                                  uint8_t *destination,
                                                  size_t capacity,
                                                  size_t stride_bytes,
                                                  struct EmuellaJ2kError **error_output);

/**
 * Copy opt-in work observations; return UNSUPPORTED without modifying output
 * when collection was disabled for this image.
 *
 * # Safety
 * `image` must be null or an exact live image handle from this library,
 * kept alive without destruction throughout the call. Concurrent immutable
 * observations are allowed. `output` must provide writable storage for one value of its
 * declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_image_decode_work(const struct EmuellaJ2kImage *image,
                                               struct EmuellaJ2kDecodeWorkV0 *output,
                                               struct EmuellaJ2kError **error_output);

/**
 * Destroy an immutable decoded image.
 *
 * # Safety
 * `image` must be null or the exact live image handle returned by this
 * library. A non-null handle transfers ownership back exactly once; all calls,
 * callbacks and borrowed observations using it must have quiesced. It must not
 * be used again or destroyed concurrently.
 */
void emuella_j2k_image_destroy(struct EmuellaJ2kImage *image);

/**
 * Copy decoded image properties into caller-owned storage.
 *
 * # Safety
 * `image` must be null or an exact live image handle from this library,
 * kept alive without destruction throughout the call. Concurrent immutable
 * observations are allowed. `output` must provide writable storage for one value of its
 * declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_image_info(const struct EmuellaJ2kImage *image,
                                        struct EmuellaJ2kImageInfoV0 *output,
                                        struct EmuellaJ2kError **error_output);

/**
 * Copy one inspected component descriptor into caller-owned storage.
 *
 * # Safety
 * `inspection` must be null or an exact live inspection handle from this library,
 * kept alive without destruction throughout the call. Concurrent immutable
 * observations are allowed. `output` must provide writable storage for one value of its
 * declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_inspection_component_info(const struct EmuellaJ2kInspection *inspection,
                                                       uint16_t component,
                                                       struct EmuellaJ2kComponentInfoV0 *output,
                                                       struct EmuellaJ2kError **error_output);

/**
 * Destroy an immutable inspection handle.
 *
 * # Safety
 * `inspection` must be null or the exact live inspection handle returned by this
 * library. A non-null handle transfers ownership back exactly once; all calls,
 * callbacks and borrowed observations using it must have quiesced. It must not
 * be used again or destroyed concurrently.
 */
void emuella_j2k_inspection_destroy(struct EmuellaJ2kInspection *inspection);

/**
 * Copy reference-image properties into caller-owned storage.
 *
 * # Safety
 * `inspection` must be null or an exact live inspection handle from this library,
 * kept alive without destruction throughout the call. Concurrent immutable
 * observations are allowed. `output` must provide writable storage for one value of its
 * declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_inspection_image_info(const struct EmuellaJ2kInspection *inspection,
                                                   struct EmuellaJ2kImageInfoV0 *output,
                                                   struct EmuellaJ2kError **error_output);

/**
 * Return a library-owned NUL-terminated package version string.
 */
const char *emuella_j2k_package_version(void);

/**
 * Create an exclusively used, reusable decode workspace.
 *
 * # Safety
 * `output` must provide writable storage for one value of its declared type.
 * A non-null `error_output` must provide writable storage for one error pointer.
 * Returned handles belong to the caller and must be released exactly once with
 * their matching destroy function; output slots do not release previous handles.
 * All non-null storage pointers must be valid for the accessed extent and
 * correctly aligned throughout this synchronous call. Writable storage must be
 * exclusively accessible and disjoint from inputs, other outputs, live handle
 * allocations and callback storage. Null or misaligned arguments are rejected
 * where checked; these checks do not establish allocation validity.
 */
EmuellaJ2kStatus emuella_j2k_workspace_create(struct EmuellaJ2kWorkspace **output,
                                              struct EmuellaJ2kError **error_output);

/**
 * Destroy an idle workspace, including a workspace poisoned by panic.
 *
 * # Safety
 * `workspace` must be null or the exact live workspace handle returned by this
 * library. A non-null handle transfers ownership back exactly once; all calls,
 * callbacks and borrowed observations using it must have quiesced. It must not
 * be used again or destroyed concurrently.
 */
void emuella_j2k_workspace_destroy(struct EmuellaJ2kWorkspace *workspace);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMUELLA_J2K_H */
