/*
 * Experimental Emuella JPEG 2000 C ABI, version zero.
 *
 * Every non-null pointer must remain valid and correctly aligned for its
 * complete synchronous call. Writable outputs must not overlap one another,
 * input storage, Rust-owned handles or callback destinations. An opaque handle
 * must be the exact live value returned by this library and must be destroyed
 * exactly once after all calls using it have quiesced; destroy accepts null.
 *
 * A decoder borrows the source context until decoder destruction. The source
 * bytes, length and context identity must remain unchanged, and read_at must be
 * safe for concurrent invocation, fill the requested range completely, retain
 * no destination pointer, avoid related-handle re-entry and return without
 * unwinding. See the complete contract at
 * https://github.com/emuella/emuella-j2k/blob/main/docs/c-abi-safety-contract.md.
 */


#ifndef EMUELLA_J2K_H
#define EMUELLA_J2K_H

/* Generated by cbindgen 0.29.4. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Experimental ABI version. Major zero carries no compatibility promise.
 */
#define EMUELLA_J2K_ABI_VERSION 0

#define EMUELLA_J2K_ENDIAN_BIG 2

#define EMUELLA_J2K_ENDIAN_LITTLE 1

#define EMUELLA_J2K_ENDIAN_NONE 0

typedef struct EmuellaJ2kDecoder EmuellaJ2kDecoder;

typedef struct EmuellaJ2kError EmuellaJ2kError;

typedef struct EmuellaJ2kImage EmuellaJ2kImage;

typedef struct EmuellaJ2kInspection EmuellaJ2kInspection;

typedef struct EmuellaJ2kWorkspace EmuellaJ2kWorkspace;

typedef uint32_t EmuellaJ2kStatus;

/**
 * One-component decode request in full-resolution image-relative coordinates.
 */
typedef struct EmuellaJ2kDecodeRequestV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint16_t component;
  /**
   * Zero means all quality layers; otherwise the leading layer count.
   */
  uint16_t max_quality_layers;
  uint32_t x;
  uint32_t y;
  uint32_t width;
  uint32_t height;
  uint8_t discard_levels;
  uint8_t reserved_bytes[7];
} EmuellaJ2kDecodeRequestV0;

/**
 * A positioned-read callback fills the complete requested destination range.
 * Any non-zero return is translated to source I/O failure.
 */
typedef EmuellaJ2kStatus (*EmuellaJ2kReadAtFn)(void *context,
                                               uint64_t offset,
                                               uint8_t *destination,
                                               size_t length);

/**
 * Consumer-owned positioned source descriptor borrowed by a decoder.
 */
typedef struct EmuellaJ2kSourceV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint64_t length;
  void *context;
  EmuellaJ2kReadAtFn read_at;
} EmuellaJ2kSourceV0;

/**
 * Native raw-component geometry and sample representation.
 */
typedef struct EmuellaJ2kComponentInfoV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint16_t source_component;
  uint8_t bits_per_sample;
  uint8_t is_signed;
  uint8_t byte_order;
  uint8_t horizontal_separation;
  uint8_t vertical_separation;
  uint8_t reserved_byte;
  uint32_t width;
  uint32_t height;
  uint32_t x_origin;
  uint32_t y_origin;
} EmuellaJ2kComponentInfoV0;

/**
 * Reference-image properties or decoded single-plane properties.
 */
typedef struct EmuellaJ2kImageInfoV0 {
  size_t struct_size;
  uint32_t abi_version;
  uint32_t reserved;
  uint32_t width;
  uint32_t height;
  uint16_t component_count;
  uint8_t bits_per_sample;
  uint8_t is_signed;
  uint8_t byte_order;
  uint8_t reserved_bytes[7];
} EmuellaJ2kImageInfoV0;

#define EMUELLA_J2K_STATUS_INTERNAL 6

#define EMUELLA_J2K_STATUS_INVALID_ARGUMENT 1

#define EMUELLA_J2K_STATUS_INVALID_INPUT 2

#define EMUELLA_J2K_STATUS_OK 0

#define EMUELLA_J2K_STATUS_PANIC 7

#define EMUELLA_J2K_STATUS_RESOURCE_LIMIT 5

#define EMUELLA_J2K_STATUS_SOURCE_IO 4

#define EMUELLA_J2K_STATUS_UNSUPPORTED 3

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t emuella_j2k_abi_version(void);

/**
 * Decode one component region into a new immutable Rust-owned image.
 */
EmuellaJ2kStatus emuella_j2k_decode_component_region(const struct EmuellaJ2kDecoder *decoder,
                                                     const struct EmuellaJ2kWorkspace *workspace,
                                                     const struct EmuellaJ2kDecodeRequestV0 *request,
                                                     struct EmuellaJ2kImage **output,
                                                     struct EmuellaJ2kError **error_output);

/**
 * Create a decoder that borrows the source descriptor's context and callback.
 */
EmuellaJ2kStatus emuella_j2k_decoder_create(const struct EmuellaJ2kSourceV0 *source,
                                            struct EmuellaJ2kDecoder **output,
                                            struct EmuellaJ2kError **error_output);

/**
 * Destroy a decoder after all calls and callbacks using it have quiesced.
 */
void emuella_j2k_decoder_destroy(struct EmuellaJ2kDecoder *decoder);

/**
 * Inspect raw Part 1 geometry without decoding packet bodies.
 */
EmuellaJ2kStatus emuella_j2k_decoder_inspect(const struct EmuellaJ2kDecoder *decoder,
                                             struct EmuellaJ2kInspection **output,
                                             struct EmuellaJ2kError **error_output);

/**
 * Destroy an immutable diagnostic handle.
 */
void emuella_j2k_error_destroy(struct EmuellaJ2kError *error);

/**
 * Copy the complete NUL-terminated UTF-8 diagnostic into caller storage.
 */
EmuellaJ2kStatus emuella_j2k_error_message_copy(const struct EmuellaJ2kError *error,
                                                uint8_t *destination,
                                                size_t capacity);

/**
 * Return the diagnostic byte count, including its terminating NUL byte.
 */
EmuellaJ2kStatus emuella_j2k_error_message_size(const struct EmuellaJ2kError *error,
                                                size_t *output);

/**
 * Return the status retained by an immutable diagnostic handle.
 */
EmuellaJ2kStatus emuella_j2k_error_status(const struct EmuellaJ2kError *error);

/**
 * Copy the single decoded component descriptor into caller-owned storage.
 */
EmuellaJ2kStatus emuella_j2k_image_component_info(const struct EmuellaJ2kImage *image,
                                                  struct EmuellaJ2kComponentInfoV0 *output,
                                                  struct EmuellaJ2kError **error_output);

/**
 * Copy decoded rows into a bounded caller-owned buffer with explicit stride.
 */
EmuellaJ2kStatus emuella_j2k_image_copy(const struct EmuellaJ2kImage *image,
                                        uint8_t *destination,
                                        size_t capacity,
                                        size_t stride_bytes,
                                        struct EmuellaJ2kError **error_output);

/**
 * Destroy an immutable decoded image.
 */
void emuella_j2k_image_destroy(struct EmuellaJ2kImage *image);

/**
 * Copy decoded image properties into caller-owned storage.
 */
EmuellaJ2kStatus emuella_j2k_image_info(const struct EmuellaJ2kImage *image,
                                        struct EmuellaJ2kImageInfoV0 *output,
                                        struct EmuellaJ2kError **error_output);

/**
 * Copy one inspected component descriptor into caller-owned storage.
 */
EmuellaJ2kStatus emuella_j2k_inspection_component_info(const struct EmuellaJ2kInspection *inspection,
                                                       uint16_t component,
                                                       struct EmuellaJ2kComponentInfoV0 *output,
                                                       struct EmuellaJ2kError **error_output);

/**
 * Destroy an immutable inspection handle.
 */
void emuella_j2k_inspection_destroy(struct EmuellaJ2kInspection *inspection);

/**
 * Copy reference-image properties into caller-owned storage.
 */
EmuellaJ2kStatus emuella_j2k_inspection_image_info(const struct EmuellaJ2kInspection *inspection,
                                                   struct EmuellaJ2kImageInfoV0 *output,
                                                   struct EmuellaJ2kError **error_output);

/**
 * Return a library-owned NUL-terminated package version string.
 */
const char *emuella_j2k_package_version(void);

/**
 * Create an exclusively used, reusable decode workspace.
 */
EmuellaJ2kStatus emuella_j2k_workspace_create(struct EmuellaJ2kWorkspace **output,
                                              struct EmuellaJ2kError **error_output);

/**
 * Destroy an idle workspace, including a workspace poisoned by panic.
 */
void emuella_j2k_workspace_destroy(struct EmuellaJ2kWorkspace *workspace);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMUELLA_J2K_H */
